import type { GetStaticProps, NextPage } from 'next'
import Link from 'next/link'

import fs from 'fs'
import { join } from 'path'
import matter from 'gray-matter'

import { writingFilePaths, WRITINGS_PATH } from 'utils/mdxUtils'
import Layout from 'components/Layout'
import { ExampleComponent } from 'components/ExampleComponent'
import React from 'react'

interface WritingInterface {
  content: string
  data: {
    title: string
    description: string
  }
  filePath: string
}

type Props = {
  writings: WritingInterface[]
}

const Writings: NextPage<Props> = ({ writings }): JSX.Element => {
  console.table(writings)
  return (
    <Layout title='Writings'>
      <section className='grid min-h-screen place-items-center'>
        <ExampleComponent title='writings' />
        <article>Articles section</article>
        <p>
          Click the link below to navigate to a page generated by{' '}
          <code>next-mdx-remote</code>.
        </p>
        <ul>
          {writings.map((writing) => (
            <li key={writing.filePath}>
              <Link
                as={`/writings/${writing.filePath.replace(/\.mdx?$/, '')}`}
                href={`/writings/[slug]`}
              >
                <a>{writing.data.title}</a>
              </Link>
            </li>
          ))}
        </ul>
      </section>
    </Layout>
  )
}
export default Writings

export const getStaticProps: GetStaticProps = async () => {
  const writings = writingFilePaths.map((filePath) => {
    const source = fs.readFileSync(join(WRITINGS_PATH, filePath))
    const { content, data } = matter(source)

    return { content, data, filePath }
  })

  return { props: { writings } }
}
