import Head from 'next/head'

type Props = {
  pageTitle: string
}

export const Header: React.FC<Props> = (props): JSX.Element => {
  return (
    <Head>
      <title>{props.pageTitle} | CelloWorld</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}
