import { Fragment, ReactElement } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'

import { ExampleComponent } from 'components/ExampleComponent'

const Home: NextPage = (): ReactElement => {
  return (
    <Fragment>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main className='grid w-full max-w-full min-h-screen mx-auto bg-gradient-to-br from-gray-50 to-gray-100 place-items-center'>
        <ExampleComponent title='Cello, World!' />
      </main>
    </Fragment>
  )
}

export default Home
