import Head from 'next/head'

type Props = {
  title: string
}

export const Header: React.FC<Props> = ({ title }): JSX.Element => {
  return (
    <Head>
      <title>{title} | CelloWorld</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>
  )
}
