import Head from 'next/head'
import { Fragment } from 'react'
import { Nav } from './Nav'
type Props = {
  title?: string
  children: React.ReactNode
}

const Layout: React.FC<Props> = ({ title = 'Home', children }) => {
  return (
    <Fragment>
      <Head>
        <title>{title} | CelloWorld</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='bg-black'>
        <div className='min-h-screen mx-auto max-w-7xl FuturaPT'>
          <Nav />
          <main>{children}</main>
        </div>
      </div>
    </Fragment>
  )
}

export default Layout
